# Pending Items to Solve

- When running and attempting to connect to Sky Safari Plus 7 after a short period 
```
  Traceback (most recent call last):
  File "/home/pi/longsight/telescope_server.py", line 726, in <module>
    data += connection.recv(16)
  TypeError: can only concatenate str (not "bytes") to str
```

# Items to Check once it runs
Did the refactoring to astropy provide the right values?
  
